
# Load libraries
library(haven)
library(plyr)
library(janitor)
library(tidyr)
library(tidyverse)
library(devtools)
library(dplyr)
library(ggplot2)
library(magrittr)
#library(car)
library(openxlsx)
library(collapse)
library(missRanger)
library(autoMrP)
library(parallel)
library(sf)
library(caret)
library(tidyr)
library(extrafont)
library(ggpubr)

wdFig <- "C:/Users/s.levi/OneDrive - Hertie School/Original Articles/Unpublished/Local attitudes/Figures"

source("Code/local_preProcessSNB.R")
source("Code/local_addAreaCode.R")
source("Code/local_createContextData.R")
source("Code/local_createPowerData.R")
source("Code/local_getCensusData.R")
source("Code/local_addGKZf.R")
source("Code/local_getElectionData.R")
source("Code/local_addCensusVars.R")
source("Code/local_addSocioDemoData.R")
source("Code/local_createIndividualData.R")
source("Code/local_addBinaryOutcomeVariables.R")
source("Code/local_checkContext.R")
source("Code/local_imputeNAs.R")
source("Code/local_addPLZ.R")
source("Code/local_scaleBerlinCensus.R")
source("Code/local_preProcessSommer.R")
source("Code/local_createIndividualData_heat.R")
source("Code/local_getHeatData.R")
source("Code/local_getOtherKommuneData.R")
source("Code/local_scaleHamburgCensus.R")
source("Code/local_scaleMunichCensus.R")
source("Code/local_add2021data.R")